spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cook_pro
    username: root
    password:
      initialization-mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always